import Layout from "pages/components/layout";
import PostList from "pages/components/postList";

export default function Home({ posts }) {
    return (
    <>
        <Layout title="Dev Gallery">
            <h3>All Posts:</h3>
            {/* <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Condimentum mattis pellentesque id nibh tortor id. Id diam maecenas ultricies mi eget. Bibendum at varius vel pharetra vel turpis nunc. Purus ut faucibus pulvinar elementum integer enim neque. Quis lectus nulla at volutpat diam ut venenatis tellus in. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Id faucibus nisl tincidunt eget nullam non nisi est sit. Massa tincidunt nunc pulvinar sapien et ligula. Quam nulla porttitor massa id neque aliquam.</p>
            <p>Felis eget nunc lobortis mattis aliquam faucibus purus in massa. Dolor sit amet consectetur adipiscing elit. Fermentum posuere urna nec tincidunt praesent. Sit amet facilisis magna etiam tempor. Eros in cursus turpis massa tincidunt dui ut ornare. Nam aliquam sem et tortor. Nulla malesuada pellentesque elit eget gravida cum sociis natoque. Pellentesque eu tincidunt tortor aliquam nulla facilisi. Tempor orci dapibus ultrices in. Pharetra magna ac placerat vestibulum lectus mauris ultrices. Scelerisque felis imperdiet proin fermentum leo. Tempus urna et pharetra pharetra massa. Ac ut consequat semper viverra nam libero justo laoreet. Risus in hendrerit gravida rutrum. Fermentum leo vel orci porta non pulvinar. Habitant morbi tristique senectus et netus et. In hac habitasse platea dictumst quisque sagittis.</p>
            <p>Vitae justo eget magna fermentum. Maecenas pharetra convallis posuere morbi leo urna molestie at. Tellus in metus vulputate eu scelerisque. Amet nisl purus in mollis nunc sed. Sodales ut eu sem integer vitae justo eget. Diam donec adipiscing tristique risus nec feugiat in fermentum. Morbi tristique senectus et netus et malesuada fames. Magnis dis parturient montes nascetur ridiculus. Morbi leo urna molestie at elementum. Montes nascetur ridiculus mus mauris vitae ultricies leo. Odio morbi quis commodo odio aenean. Parturient montes nascetur ridiculus mus. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Ipsum dolor sit amet consectetur adipiscing elit duis tristique. Felis bibendum ut tristique et egestas quis ipsum. Facilisi nullam vehicula ipsum a arcu cursus vitae congue mauris. Proin libero nunc consequat interdum varius. Varius duis at consectetur lorem donec massa sapien faucibus et. Adipiscing enim eu turpis egestas pretium aenean pharetra. Orci nulla pellentesque dignissim enim.</p>
            <p>Duis convallis convallis tellus id interdum velit laoreet. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Sit amet massa vitae tortor. Laoreet sit amet cursus sit amet dictum. Egestas fringilla phasellus faucibus scelerisque eleifend. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Enim neque volutpat ac tincidunt vitae semper. Commodo odio aenean sed adipiscing diam donec. Nibh ipsum consequat nisl vel pretium lectus quam. Nulla pellentesque dignissim enim sit amet venenatis. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Curabitur gravida arcu ac tortor dignissim convallis aenean. Id aliquet risus feugiat in ante metus. Ultrices tincidunt arcu non sodales neque sodales ut etiam. Leo a diam sollicitudin tempor id eu nisl. In hac habitasse platea dictumst. Diam vel quam elementum pulvinar etiam. Pellentesque habitant morbi tristique senectus. Varius quam quisque id diam vel quam elementum. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui.</p>
            <p>A diam sollicitudin tempor id eu. Sem nulla pharetra diam sit amet nisl suscipit. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. At volutpat diam ut venenatis tellus. Quis blandit turpis cursus in hac habitasse. Ac tincidunt vitae semper quis lectus. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. In nibh mauris cursus mattis. Non arcu risus quis varius quam quisque id diam. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Ultrices eros in cursus turpis massa. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. Augue mauris augue neque gravida in fermentum.</p>
            <p>Turpis egestas maecenas pharetra convallis posuere morbi leo. Tincidunt arcu non sodales neque sodales ut etiam sit. A diam maecenas sed enim ut sem viverra aliquet. Congue eu consequat ac felis donec et odio pellentesque diam. Sed sed risus pretium quam vulputate dignissim. Blandit massa enim nec dui nunc mattis enim ut tellus. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Erat pellentesque adipiscing commodo elit at imperdiet. Purus gravida quis blandit turpis cursus in. Aliquam ultrices sagittis orci a scelerisque.</p>
            <p>Duis convallis convallis tellus id interdum velit laoreet. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Sit amet massa vitae tortor. Laoreet sit amet cursus sit amet dictum. Egestas fringilla phasellus faucibus scelerisque eleifend. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Enim neque volutpat ac tincidunt vitae semper. Commodo odio aenean sed adipiscing diam donec. Nibh ipsum consequat nisl vel pretium lectus quam. Nulla pellentesque dignissim enim sit amet venenatis. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Curabitur gravida arcu ac tortor dignissim convallis aenean. Id aliquet risus feugiat in ante metus. Ultrices tincidunt arcu non sodales neque sodales ut etiam. Leo a diam sollicitudin tempor id eu nisl. In hac habitasse platea dictumst. Diam vel quam elementum pulvinar etiam. Pellentesque habitant morbi tristique senectus. Varius quam quisque id diam vel quam elementum. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui.</p>
            <p>A diam sollicitudin tempor id eu. Sem nulla pharetra diam sit amet nisl suscipit. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. At volutpat diam ut venenatis tellus. Quis blandit turpis cursus in hac habitasse. Ac tincidunt vitae semper quis lectus. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo. In nibh mauris cursus mattis. Non arcu risus quis varius quam quisque id diam. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Ultrices eros in cursus turpis massa. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. Augue mauris augue neque gravida in fermentum.</p>
            <p>Turpis egestas maecenas pharetra convallis posuere morbi leo. Tincidunt arcu non sodales neque sodales ut etiam sit. A diam maecenas sed enim ut sem viverra aliquet. Congue eu consequat ac felis donec et odio pellentesque diam. Sed sed risus pretium quam vulputate dignissim. Blandit massa enim nec dui nunc mattis enim ut tellus. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Erat pellentesque adipiscing commodo elit at imperdiet. Purus gravida quis blandit turpis cursus in. Aliquam ultrices sagittis orci a scelerisque.</p> */}

            <PostList posts={ posts } />
        </Layout>
    </>
    );
}
  
export async function getStaticProps() {
    const res = await fetch(process.env.BASE_URL + "/api/post/all");
    const posts = await res.json();
    
    return {
        props: {
            posts,
        },
    }
}